### ISSUE TITLE
Error while using Mongo latest version  v4.2.1. $eval command is removed after version 4.2.0

### ISSUE THREAD

**Issue by vikksa** [hzpz/mongeez-spring-boot-starter#13]
I am using latest version of Mongo v4.2.1 and in latest version the **$eval** command is removed so it throwing the below error: 

> Caused by: com.mongodb.MongoCommandException: Command failed with error 59 (CommandNotFound): 'no such command: '$eval'' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "no such command: '$eval'", "code" : 59, "codeName" : "CommandNotFound" }
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:293) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:242) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:213) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:186) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:158) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:148) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.operation.CommandWriteOperation.execute(CommandWriteOperation.java:55) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:193) ~[mongodb-driver-3.8.2.jar:na]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:166) ~[mongodb-driver-3.8.2.jar:na]
	at com.mongodb.DB.executeCommand(DB.java:731) ~[mongodb-driver-3.8.2.jar:na]
	at com.mongodb.DB.doEval(DB.java:570) ~[mongodb-driver-3.8.2.jar:na]
	at com.mongodb.DB.eval(DB.java:584) ~[mongodb-driver-3.8.2.jar:na]
	at org.mongeez.dao.MongeezDao.runScript(MongeezDao.java:135) ~[mongeez-0.9.6.jar:na]
	at org.mongeez.commands.Script.run(Script.java:32) ~[mongeez-0.9.6.jar:na]
	at org.mongeez.ChangeSetExecutor.execute(ChangeSetExecutor.java:60) ~[mongeez-0.9.6.jar:na]
	at org.mongeez.ChangeSetExecutor.execute(ChangeSetExecutor.java:45) ~[mongeez-0.9.6.jar:na]
	at org.mongeez.Mongeez.process(Mongeez.java:45) ~[mongeez-0.9.6.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1904) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1846) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774) ~[spring-beans-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	... 68 common frames omitted

**Comment by hzpz** [comment]
This project is only a starter for Spring Boot that configures and runs Mongeez. All access to MongoDB is done entirely by Mongeez. There already is an issue on the Mongeez repository [about the removal of eval](https://github.com/mongeez/mongeez/issues/75). Unfortunatelly it seems, that Mongeez hasn't been maintained for years. 

Short of starting to maintain Mongeez, there is nothing I can do about this issue, sorry.
